### ISSUE TITLE
Rapport

### ISSUE THREAD

**Issue by micaelacarlsson** [raptice/SpaceSnake#155]
Översikts-UML
Sammanfattning/abstract på 1/4 A4 + Resultat
Användningsmanual
JAR
Kod

**Comment by micaelacarlsson** [comment]
Modellbeskrivning

**Comment by di0svgu** [comment]
Ingen deadline för JavaDoc och kod än så där kan vi fortsätta putsa men rapporten är inskickad så detta avslutar jag.
