### ISSUE TITLE
Lägg till objekt i världen - kolla kollisioner/närhet till andra objekt vid skapelse

### ISSUE THREAD

**Issue by micaelacarlsson** [raptice/SpaceSnake#71]

**Comment by micaelacarlsson** [comment]
Funkar att lägga till saker, men vi behöver göra så att de skapas på random ställe i världen

**Comment by micaelacarlsson** [comment]
Randomisering är klar. Vi behöver kolla så att objekt inte skapas på varandra.

**Comment by micaelacarlsson** [comment]
Randomiseringen gör att vissa objekt skapas utanför världen eftersom den använder worldSize och skapar saker inom en kvadrat istället för en cirkel.

**Comment by di0svgu** [comment]
Rymdpolära koordinater kan lösa det men mycket lättare är att slumpa de inom en kvadrat och sedan slumpa om de som hamnade utanför cirkeln.

**Comment by micaelacarlsson** [comment]
Kollar väl fortfarande inte om de skapas på varandra?
